US10 – Map Overview
BirkBee/outivities-app pull request #29
Opened 2023-12-10 10:08 UTC by Julia-Pickel

– added coordinates (latitude and longitude) to the dummy data / `initialOutivities`
– added `Map`- and `CurrentOutivityMarker`-component 
– added Map to details page to display the location of the actual _Outivity_
– there is a `StyledHideButton` on the details page that can be clicked to show or hide the map section

– implemented API to fetch the correspondingly coordinates (latitude and longitude) of the `outivityArea` input field 
– edited the `UpdateOutivityDetails`- and the `CreateOutivity`-functions according to the fetch and to be able to display also the location of new or/and updated `Outivities` on the map

2023-12-10 17:44 UTC, luederb requested changes
Hey, nice work with the implementation of the map. 
I think the center - function of the map and also the fly.to didn't really work as intended. I actually forked your app and wrote the code, so that it should work now. I make the changes in the PR but if you find that to confusing (because I changed quite a lot), you can also look at my forked repo: https://github.com/luederb/outivities-app
Hope this helps and that the map works afterwards !!

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +      setCurrentPosition(event.latlng);
```suggestion
       const userCoordinates = event.latlng;
       onSetUserPosition({ lat: userCoordinates.lat, lng: userCoordinates.lng });
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +      map.flyTo(event.latlng, map.getZoom());
```suggestion
      map.flyTo([position[0], position[1]], map.getZoom(12));
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +  const [currentPosition, setCurrentPosition] = useState(position);
```suggestion
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +    if (position) {
You already always have a position
```suggestion
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +      setCurrentPosition(position);
Das macht ihr oben dann im locationfound map ding...
```suggestion
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +      map.flyTo(position, map.getZoom());
Das macht ihr auch bereits oben dann
```suggestion
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +    currentPosition && (
Der Marker sollte doch lieber die Position von eurer Outivity anzeigen, oder?
```suggestion
    position && (
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +      <Marker position={currentPosition} icon={blueIcon}>
Hier auch die position aus der outivity
```suggestion
      <Marker position={position} icon={blueIcon}>
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +import { useEffect, useState } from "react";
useState braucht ihr hier dann nicht mehr
```suggestion
import { useEffect } from "react";
```

2023-12-10 17:44 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +export default function CurrentOutivityMarker({ outivity, position }) {
hier müsst ihr die handler-function noch mitgeben, da wir nicht die state-setter-function direkt mitgeben dürfen ...
```suggestion
export default function CurrentOutivityMarker({ outivity, position, onSetUserPosition }) {
```

2023-12-10 17:44 UTC, luederb commented on components/Map/index.js
> +
Damit wir die userPosition in der CurrentOutivityMarker.js setzen können, müssen wir hier eine handler-function mitgeben: 
```suggestion
function handleSetUserPosition(userCoordinates) {
    setUserPosition(userCoordinates);
  }
```

2023-12-10 17:44 UTC, luederb commented on components/Map/index.js
> +            position={[outivity.lat, outivity.long]}
und die handler-function hier auch mitgeben:
```suggestion
            position={[outivity.lat, outivity.long]}
            onSetUserPosition={handleSetUserPosition}
```

2023-12-10 19:13 UTC, luederb reviewed
Hey, mir ist noch aufgefallen, dass ihr nicht useLocalStorageState, sondern nur useLocalStorage nutzt. Muss glaube ich mit State sein. Dann gehts auch wieder ^^

2023-12-10 19:13 UTC, luederb commented on components/Map/index.js
> +import useLocalStorage from "use-local-storage";
```suggestion
import useLocalStorageState from "use-local-storage-state";
```

2023-12-10 19:13 UTC, luederb commented on components/Map/index.js
> +  const [userPosition, setUserPosition] = useLocalStorage("userPosition", {
```suggestion
  const [userPosition, setUserPosition] = useLocalStorageState("userPosition", {
```

2023-12-10 21:08 UTC, Julia-Pickel commented
@luederb wow, many thanks for the review and taking the time to even rewrite some code!!! 💙

We actually noticed this ourselves (in the beginning we simply thought it was an issue due to our computer's settings and didn't double check it).

However, we've decided to completely remove the `fly.to` hook and user location. 
In our opinion, it is a better user experience to show the actual _Outivity_ location directly on the details page, as it can be irritating (especially with the hide/show button) to always start at your location.

But we're planing to use it in our overall maps page. So your efforts were definitely not a waste of time!! 
Thanks again 🙌

2023-12-11 00:07 UTC, luederb requested changes
I see, yes that's a fair point. It's better like this, that the map just starts directly a the position of the outivity. No need to fly to it from the user position. Maybe makes more sence when you wanna show a map while the user creates a new outivity? then the map starts on the user location and changes to the poistion (if found), once the user entered a location? Or as you said on a overall maps page ... 👍
Glad that my code / review helped 😊
However, now I don't see the value of the CurrentOutivityMarker.js - component anymore, since the only difference of the CurrentMarker to the normal Marker is the color of the icon. I made a suggestion in the code on how to better and also cleaner implement that into the code. 
Hope that helps 👍

2023-12-11 00:07 UTC, luederb commented on components/Map/index.js
> +            icon={greyIcon}
As far as I see it, the only reason you have the CurrentOutivityMarker now is, that the icon-color is blue, not grey, right? The center of the map is set in line 13 to the slug-outivity, that you give the Map function as a prop, anyway. So I think it would be a much cleaner code if you just made the type of icon conditional to the currentOutivity.id. Then you can delete the entire CurrentOutivityMaker.js, right? 
The condition should be something like this: (I'm not sure about the correct syntax right now - it's late, I shouldn't review code right now 😅
```suggestion
            icon={outivity.id === currentOutivity.id ? blueIcon : greyIcon}
```

2023-12-11 00:07 UTC, luederb commented on components/Map/index.js
> +        ) : (
```suggestion
```

2023-12-11 00:07 UTC, luederb commented on components/Map/index.js
> +        )
```suggestion
```

2023-12-11 00:07 UTC, luederb commented on components/Map/CurrentOutivityMarker.js
> +`;
Suggestion: delete the entire CurrentOutivityMarker, declare the blueIcon in the index.js and make the icon-type conditional on the currentOutivity.id when mapping over all outivities
```suggestion
```

2023-12-11 00:07 UTC, luederb commented on components/Map/index.js
> +
```suggestion
const blueIcon = new L.Icon({
  iconUrl:
    "https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-blue.png",
  shadowUrl:
    "https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png",
  iconSize: [25, 41],
  iconAnchor: [12, 41],
  popupAnchor: [1, -34],
  shadowSize: [41, 41],
});
```

2023-12-11 08:59 UTC, Julia-Pickel commented
@luederb very good point! 👌 
We've updated the code and removed the `CurrentOutivityMarker.js`

2023-12-11 09:50 UTC, luederb approved these changes
LGTM

2023-12-11 10:03 UTC, merged